### PR TITLE
Fixed the bug that the wechat qr-code can't work.

### PR DESCRIPTION
**Pull request by kuleyu**
The api link "https://api.qinco.me/api/qr?size=400&content=" is disabled，and I changed it to "https://pan.baidu.com/share/qrcode?w=400&h=400&url=", which is from BaiDu.

### CODE REVIEW

**Comment by ivan-nginx** [comment]
And what about [this pull](https://github.com/iissnan/hexo-theme-next/pull/1976)? What's the difference?

**Comment by LEAFERx** [comment]
I think both are ok except using the different qrcode generator api

**Comment by kuleyu** [comment]
Oh! haven't seen it before. They have the same effect, but maybe there are still two differences between them:
- 1. His link is 'http', mine is 'https'.
- 2. His pull is for [hexo-theme-next](https://github.com/iissnan/hexo-theme-next), a theme, and mine is for [theme-next-needmoreshare2](https://github.com/theme-next/theme-next-needmoreshare2), a single plugin。

**Comment by kuleyu** [comment]
yes!

**Comment by LEAFERx** [comment]
https is better i think

**Comment by ivan-nginx** [comment]
Ok, i'll merge it pull here and close pull with HTTP there.

**Pull request merged**
