### PR TITLE
miss iconStyle == "default" and boxForm == "vertical"

### PR DESCRIPTION
**Pull request by x22x22**
miss iconStyle == "default" and boxForm == "vertical"

### CODE REVIEW

**Comment by LEAFERx** [comment]
@x22x22 Have u tested ur change `default & vertical`?
Could u please upload a screenshot?

**Comment by x22x22** [comment]
@LEAFERx 
image

snipaste_2018-04-05_23-49-43

**Comment by sli1989** [comment]
Seems `position` is unfunctional with same margin as well. 😃

**Comment by LEAFERx** [comment]
@sli1989 well I don't change too much code from original repo.
Maybe u cloud fix it？

**Pull request merged**
