### PR TITLE
generate QR Code of WeChat Sharing from https://api.qrserver.com

### PR DESCRIPTION
**Pull request by PeichengLiu**
Solve the problem of failing to load WeChat sharing QR Code image.

### CODE REVIEW

**Comment by PeichengLiu** [comment]
Such a long time...

**Comment by LEAFERx** [comment]
sorry for my absent. I will review it asap.

**Comment by LEAFERx** [comment]
150x150 maybe too small？

**Comment by PeichengLiu** [comment]
works fine for scanning

**Comment by LEAFERx** [comment]
but maybe not good for those high definition (2k, 4k) users? Can u tell me the file size 150x150 and 400x400 are?

**Comment by PeichengLiu** [comment]
I tested it, the file size gets larger with longer URL, and clearer resolution. While both 150x150 and 400x400 costed less than 1KB data transfered.
I cared much about neither the file size, nor visual effect on high definition screen.
I just used it. And its size fitted the whole UI fine, having no problem for sacnning. That's enough.

**Comment by LEAFERx** [comment]
All right. Thanks for your contribution.

**Pull request merged**
